### ISSUE TITLE
Instructions give the same position for cogs

### ISSUE THREAD

**Issue by flsobral** [Monoblos/cogtimizer#1]
You can check it out by loading the username Kinaaba.
It only happens if loaded with the username, if you go to https://kinaaba.idleonefficiency.com/raw-data and copy the actual json it works as expected.
The owner of the profile is a guildmate, I don't know how long until he updates it, but I kept a copy of the current json.

![image](https://user-images.githubusercontent.com/6097965/231555924-f48e2218-434b-459e-ad1e-0009047a77b8.png)

**Comment by noslavde** [comment]
I too have this issue. It was fine when I still had flags on the board, but now that I've got all my cog board opened and filled, the majority of the solution's moves are saying to switch with the same position, yet references a different cog.
Edit to add:
The issue persists regardless of load method; username vs json.

**Comment by Bolero-fk** [comment]
I may have noticed a condition under which this bug occurs.
The bug occurs when the cog located at the top-leftmost coordinate (1,1) is included in the exchange.
So until this bug is fixed, in the case of an exchange of the same co-ordinates we should just exchange the cog at the co-ordinates (1,1) with that co-ordinate.

**Comment by Monoblos** [comment]
Yeah, when I developed it those spots where still locked for me and the couple of other profiles I tried back then didn't show the issue. Most likely some problem with the Index 0 somewhere. I'll try to have a look into it. 👍

**Comment by Bolero-fk** [comment]
@Monoblos 
Thank you for confirm my pull request.
However, the branch used for the github-page release seems a little wrong.
(Lines 72, 73, 74 and 76 are unnecessary)
Please check.
https://github.com/Monoblos/cogtimizer/blob/4029edb4e61b87814b224146450adb94f332ab59/CogInventory.js#L69-L76
